name = "Angular Rust"
description = "An intuitive, elegant, and lightweight Zola theme for product sites."
license = "MIT"
homepage = "https://github.com/dudochkin-victor"
min_version = "0.11.0"
demo = "https://angular-rust.github.io"

[extra]

[author]
name = "Dudochkin Victor"
homepage = "https://dudochkin-victor.github.io"
